# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

GradParamLogLik <- function(param, YT, YNT, riskNT, riskT, XNT, XT, XOR, XinterMat, epsOR) {
    .Call('_LongitSemiComp_GradParamLogLik', PACKAGE = 'LongitSemiComp', param, YT, YNT, riskNT, riskT, XNT, XT, XOR, XinterMat, epsOR)
}

GradParamLogLikPersTimeDep <- function(param, ID, TM, YT, YNT, XNT, XT, XOR, epsOR) {
    .Call('_LongitSemiComp_GradParamLogLikPersTimeDep', PACKAGE = 'LongitSemiComp', param, ID, TM, YT, YNT, XNT, XT, XOR, epsOR)
}

GradParamLogLikTimeDep <- function(param, ID, TM, YT, YNT, XNT, XT, XOR, epsOR) {
    .Call('_LongitSemiComp_GradParamLogLikTimeDep', PACKAGE = 'LongitSemiComp', param, ID, TM, YT, YNT, XNT, XT, XOR, epsOR)
}

GradPenalLogLik <- function(param, YNT, riskNT, riskT, YT, XNT, XT, XOR, XinterMat, TimeBase, TimePen, lambda, epsOR) {
    .Call('_LongitSemiComp_GradPenalLogLik', PACKAGE = 'LongitSemiComp', param, YNT, riskNT, riskT, YT, XNT, XT, XOR, XinterMat, TimeBase, TimePen, lambda, epsOR)
}

GradPenalLogLikPers <- function(param, YNT, riskNT, riskT, YT, XNT, XT, XOR, XinterMat, TimeBase, TimePen, lambda, epsOR) {
    .Call('_LongitSemiComp_GradPenalLogLikPers', PACKAGE = 'LongitSemiComp', param, YNT, riskNT, riskT, YT, XNT, XT, XOR, XinterMat, TimeBase, TimePen, lambda, epsOR)
}

GradPenalLogLikPersTimeDep <- function(param, ID, TM, YT, YNT, XNT, XT, XOR, TimeBase, TimePen, lambda, epsOR) {
    .Call('_LongitSemiComp_GradPenalLogLikPersTimeDep', PACKAGE = 'LongitSemiComp', param, ID, TM, YT, YNT, XNT, XT, XOR, TimeBase, TimePen, lambda, epsOR)
}

GradPenalLogLikTimeDep <- function(param, ID, TM, YT, YNT, XNT, XT, XOR, TimeBase, TimePen, lambda, epsOR) {
    .Call('_LongitSemiComp_GradPenalLogLikTimeDep', PACKAGE = 'LongitSemiComp', param, ID, TM, YT, YNT, XNT, XT, XOR, TimeBase, TimePen, lambda, epsOR)
}

OddsRatioTime <- function(YNT, YT, riskNT, riskT) {
    .Call('_LongitSemiComp_OddsRatioTime', PACKAGE = 'LongitSemiComp', YNT, YT, riskNT, riskT)
}

ParamLogLik <- function(param, YT, YNT, riskNT, riskT, XNT, XT, XOR, XinterMat, epsOR) {
    .Call('_LongitSemiComp_ParamLogLik', PACKAGE = 'LongitSemiComp', param, YT, YNT, riskNT, riskT, XNT, XT, XOR, XinterMat, epsOR)
}

ParamLogLikTimeDep <- function(param, ID, TM, YT, YNT, XNT, XT, XOR, epsOR) {
    .Call('_LongitSemiComp_ParamLogLikTimeDep', PACKAGE = 'LongitSemiComp', param, ID, TM, YT, YNT, XNT, XT, XOR, epsOR)
}

PenalLogLik <- function(param, YT, YNT, riskNT, riskT, XNT, XT, XOR, XinterMat, TimeBase, TimePen, lambda, epsOR) {
    .Call('_LongitSemiComp_PenalLogLik', PACKAGE = 'LongitSemiComp', param, YT, YNT, riskNT, riskT, XNT, XT, XOR, XinterMat, TimeBase, TimePen, lambda, epsOR)
}

PenalLogLikTimeDep <- function(param, ID, TM, YT, YNT, XNT, XT, XOR, TimeBase, TimePen, lambda, epsOR) {
    .Call('_LongitSemiComp_PenalLogLikTimeDep', PACKAGE = 'LongitSemiComp', param, ID, TM, YT, YNT, XNT, XT, XOR, TimeBase, TimePen, lambda, epsOR)
}

